name: "Build and run tests (CI)"

on:
  push:
    # On which branch
    branches: ["main"]
    # On which files
    # paths: ["scripts/scripts.js", "styles/styles.scss"]
  schedule:
    # Every Tuesday at 1PM UTC
    - cron: "0 13 * * 2"
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: "Build library and run unit-tests with Maven"
        run: ./mvnw --batch-mode --update-snapshots clean verify package
      - name: "Build example"
        run: ./mvnw --batch-mode --update-snapshots clean package

